### ISSUE TITLE
Latest Version Published on NPM?

### ISSUE THREAD

**Issue by nelsonic** [nak2k/node-npm-install-from-s3#117]
Hi @nak2k!
We are interested in _using_ this module for a project we are working on. 
However from viewing NPM: https://www.npmjs.com/package/npm-install-from-s3
![image](https://user-images.githubusercontent.com/194400/31946839-923b8b2e-b8db-11e7-9505-7b8f6d79cf55.png)
It _appears_ that the NPM package/module has not been updated/published for the past 2 years.

> Are you planning on updating NPM? (_thanks!_)

**Comment by nak2k** [comment]
Hi @nelsonic!

Thank you for your interest in this package.

I have published a new version now.

I’d be happy if I could get your feedback.

**Comment by nelsonic** [comment]
@nak2k thanks for getting back to us! 
It could be useful to get a bit more detailed Docs in the readme for the expected format of the package on S3. From reading your code it appears that you are looking for a `.tgz` (_zipped file_)
https://github.com/nak2k/node-npm-install-from-s3/blob/b192f404b8932e2cd3e973f56cf76f9f66ed339a/lib/installFromS3.js#L69
Should the person _publishing_ the module/package to S3 be zipping it using Tar...? (_thanks!_)

**Comment by nak2k** [comment]
@nelsonic

I have released v0.0.3 that includes improved README and performance improvements.

Thanks for the feedback!
